site_name: My Notes
site_url: https://rwxlog.github.io/mynotes/
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences # REQUIRED for correct rendering of fenced code blocks
  - pymdownx.details
  - attr_list

nav:
  - Home: index.md
  - Career Notes:
      - 90 Day Cybersecurity: CareerNotes/90-day-cybersecurity.md
      - 90 Day WordPress: CareerNotes/90-day-wordpress.md
  - Cyber Notes:
      - Sample Note: CyberNotes/samplenote.md
  - Dev Notes:
      - LAMP Setup: DevNotes/LAMP.md
      - phpMyAdmin: DevNotes/phpMyAdmin.md
      - WP Backup (Auto): DevNotes/wp-backup-auto.md
      - WP Backup (Compressed): DevNotes/wp-backup-compressed.md
      - WP Backup (Manual): DevNotes/wp-backup.md
      - WP Database CLI: DevNotes/wp-database-cli.md
      - WP Database GUI: DevNotes/wp-database.md
      - WP Restore: DevNotes/wp-restore.md
  - Hunter Notes:
      - Sample Note: HunterNotes/samplenote.md
  - Linux Notes:
      - paclist: LinuxNotes/paclist.md
  - Tech Notes:
      - GitHub: TechNotes/GitHub.md
  - Web Notes:
      - Markdown Links: WebNotes/markdown-links.md
      - Markdown Styling: WebNotes/markdown-styling.md
      - Programing Concepts: WebNotes/programing-concepts.md
      - Share Button: WebNotes/share-button.md
      - Site Structure (Noted): WebNotes/site-structure-noted.md
      - Site Structure: WebNotes/site-structure.md
  - SSG Notes:
    - Astro: SSGNotes/astro.md
    - Docsify: SSGNotes/docsify.md
    - Docusaurus: SSGNotes/docusaurus.md
    - Eleventy (11ty): SSGNotes/eleventy.md
    - Gatsby: SSGNotes/gatsby.md
    - Gridsome: SSGNotes/gridsome.md
    - Hexo: SSGNotes/hexo.md
    - Hugo: SSGNotes/hugo.md
    - Jekyll: SSGNotes/jekyll.md
    - Lektor: SSGNotes/lektor.md
    - MkDocs: SSGNotes/mkdocs.md
    - MkDocs (GitHub Deploy): SSGNotes/mkdocs-gh.md
    - Next.js: SSGNotes/next-js.md
    - Nuxt.js: SSGNotes/nuxt-js.md
    - Pelican: SSGNotes/pelican.md
    - Vite: SSGNotes/vite.md
    - VuePress: SSGNotes/vuepress.md
  - Other Notes:
      - Sample Note: OtherNotes/samplenote.md
